Controllers/DashboardController.cs
using System.Threading.Tasks;
using CloudinaryDotNet.Actions;
using EventFinder.Interfaces;
using Microsoft.AspNetCore.Mvc;

public class DashboardController : Controller
{

    private readonly IDashboardRepository _dashboardRepository;
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly IPhotoService _photoService;

    public DashboardController(IDashboardRepository dashboardRepository,
    IHttpContextAccessor httpContextAccessor, IPhotoService photoService)
    {
        _dashboardRepository = dashboardRepository;
        _httpContextAccessor = httpContextAccessor;
        _photoService = photoService;
    }
    private void MapUserEdit(AppUser user, EditUserDashboardViewModel editVM, ImageUploadResult photoResult)
    {
        user.Id = editVM.Id;
        user.City = editVM.City;
        user.State = editVM.State;
        user.ProfileImageUrl = photoResult.Url.ToString();

    }
    public async Task<IActionResult> Index()
    {
        var userEvents = await _dashboardRepository.GetAllUserEvents();
        var dashboardViewModel = new DashboardViewModel()
        {

            Events = userEvents
        };

        return View(dashboardViewModel);

    }

    public async Task<IActionResult> EditUserProfile()
    {
        var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
        var user = await _dashboardRepository.GetUserById(curUserId);
        if (user == null) return View("Error");
        var editUserViewModel = new EditUserDashboardViewModel()
        {
            Id = curUserId,
            ProfileImageUrl = user.ProfileImageUrl,
            City = user.City,
            State = user.State
        };
        return View(editUserViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> EditUserProfile(EditUserDashboardViewModel editVM)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("", "Failed to edit profile");
            return View("EditUserProfile", editVM);
        }
        var user = await _dashboardRepository.GetByIdNoTracking(editVM.Id);

        if (user.ProfileImageUrl == "" || user.ProfileImageUrl == null) // ef is , pulling record from db and turning into an object so that we can manipulate it
        {
            var photoResult = await _photoService.AddPhotoAsync(editVM.Image);
            // Optimistic Concurrency-"Tracking Error"
            // Use No tracking
            // var userTracking = new AppUser()
            // {

            // }
            // do this instead
            MapUserEdit(user, editVM, photoResult);
            _dashboardRepository.Update(user);
            return RedirectToAction("Index");
        }
        else
        {
            try
            {
                await _photoService.DeletePhotoAsync(user.ProfileImageUrl);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "Could not delete photo");
                return View(editVM);
            }
            var photoResult = await _photoService.AddPhotoAsync(editVM.Image);
            MapUserEdit(user, editVM, photoResult);
            _dashboardRepository.Update(user);
            return RedirectToAction("Index");
        }
    }
}

Controllers/EventController.cs
using EventFinder.Interfaces;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

public class EventController : Controller

{
    private readonly IEventRepository _eventRepository;
    private readonly IPhotoService _photoService;
    private readonly IHttpContextAccessor _httpContextAccessor;
    public EventController(IEventRepository eventRepository, IPhotoService photoService, IHttpContextAccessor httpContextAccessor)
    {

        _eventRepository = eventRepository;
        _photoService = photoService;
        _httpContextAccessor = httpContextAccessor;
    }
    public async Task<IActionResult> Index()
    {
        IEnumerable<Event> events = await _eventRepository.GetAll();
        return View(events);
    }
    public async Task<IActionResult> Detail(int id)
    {

        Event foundEvent = await _eventRepository.GetByIdAsync(id);

        return View(foundEvent);

    }

    public IActionResult Create()
    {
        var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
        var CreateEventViewModel = new CreateEventViewModel { AppUserId = curUserId };
        return View(CreateEventViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Create(CreateEventViewModel eventVM)
    {

        if (ModelState.IsValid) // modelde tanımlı kurallara uygunsa
        {
            var result = await _photoService.AddPhotoAsync(eventVM.Image);
            var foundEvent = new Event // manuel mapleme
            {
                Title = eventVM.Title,
                Description = eventVM.Description,
                Image = result.Url.ToString(),
                AppUserId = eventVM.AppUserId,
                Address = new Address
                {

                    City = eventVM.Address.City,
                    State = eventVM.Address.State,
                    Street = eventVM.Address.Street

                }
            };
            _eventRepository.Add(foundEvent);
            return RedirectToAction("Index");
        }
        else
        {
            ModelState.AddModelError("", "Photo Upload Failed");
        }
        return View(eventVM);

    }

    public async Task<IActionResult> Edit(int id) // View aynı isimde olmalı Edit.cshtml
    {
        var foundEvent = await _eventRepository.GetByIdAsync(id);
        if (foundEvent == null) return View("Error");

        var eventVM = new EditEventViewModel
        { // mapping

            Title = foundEvent.Title,
            Description = foundEvent.Description,
            AddressId = foundEvent.AddressId,
            Address = foundEvent.Address,
            URL = foundEvent.Image,
            EventCategory = foundEvent.EventCategory
        };
        return View(eventVM);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, EditEventViewModel eventVM)
    {

        if (!ModelState.IsValid)
        {
            ModelState.AddModelError("", "Failed to edit club");
            return View("Edit", eventVM);
        }
        var userEvent = await _eventRepository.GetByIdAsyncNoTracking(id);

        if (userEvent != null)
        {
            try
            {
                await _photoService.DeletePhotoAsync(userEvent.Image);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Could not delete photo");
                return View(eventVM);
            }

            var photoResult = await _photoService.AddPhotoAsync(eventVM.Image);

            var foundEvent = new Event
            {
                Id = id,
                Title = eventVM.Title,
                Description = eventVM.Description,
                Image = photoResult.Url.ToString(),
                AddressId = eventVM.AddressId,
                Address = eventVM.Address,


            };
            _eventRepository.Update(foundEvent);

            return RedirectToAction("Index");
        }
        else
        {
            return View(eventVM);

        }


    }
    public async Task<IActionResult> Delete(int id)
    {
        var eventDetails = await _eventRepository.GetByIdAsync(id);
        if (eventDetails == null) return View("Error");
        return View(eventDetails);
    }
    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteEvent(int id)
    {
        var eventDetails = await _eventRepository.GetByIdAsync(id);
        if (eventDetails == null) return View("Error");
       
       _eventRepository.Delete(eventDetails);
       return RedirectToAction("Index");
    }
}

Controllers/UserController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

public class UserController : Controller
{
    private readonly IUserRepository _userRepository;
    public UserController(IUserRepository userRepository)
    {
        _userRepository = userRepository;
    }
    [HttpGet("users")]
    public async Task<IActionResult> Index()
    {
        var users = await _userRepository.GetAllUsers();
        List<UserViewModel> result = new List<UserViewModel>();
        foreach (var user in users)
        {
            var userViewModel = new UserViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                ProfileImageUrl = user.ProfileImageUrl

            };
            result.Add(userViewModel);
        }

        return View(result);
    }

    public async Task<IActionResult> Detail(string id)
    {
        var user = await _userRepository.GetUserById(id);
        var userDetailViewModel = new UserDetailViewModel()
        {
            Id = user.Id,
            UserName = user.UserName,
            ProfileImageUrl=user.ProfileImageUrl
        };

        return View(userDetailViewModel);
    }


}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventFinder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project_mvc_dotnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">EventFinder</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Event" asp-action="Index">Events</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" class="d-flex">
                                    <button class="btn btn-outline-light">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container mt-4">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-light text-center text-muted py-3 mt-auto">
        <div class="container">
            &copy; @DateTime.Now.Year - EventFinder - 
            <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-decoration-none">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>